// Sticker catalog — Fluent Emoji Flat by Microsoft (MIT License)
// Source: https://api.iconify.design/fluent-emoji-flat/{id}.svg

export const THEMES = [
  { id: 'all',         label: 'Semua',       emoji: '✨' },
  { id: 'birthday',   label: 'Ulang Tahun', emoji: '🎂' },
  { id: 'wedding',    label: 'Pernikahan',  emoji: '💍' },
  { id: 'graduation', label: 'Wisuda',      emoji: '🎓' },
  { id: 'baby',       label: 'Baby Shower', emoji: '👶' },
  { id: 'valentine',  label: 'Valentine',   emoji: '❤️' },
  { id: 'ramadan',    label: 'Ramadan',     emoji: '🌙' },
  { id: 'nature',     label: 'Alam',        emoji: '🌸' },
  { id: 'animal',     label: 'Hewan',       emoji: '🐱' },
  { id: 'celebration',label: 'Perayaan',    emoji: '🎉' },
  { id: 'christmas',  label: 'Natal',       emoji: '🎄' },
  { id: 'food',       label: 'Kuliner',     emoji: '🍰' },
  { id: 'travel',     label: 'Perjalanan',  emoji: '✈️' },
  { id: 'music',      label: 'Musik',       emoji: '🎵' },
  { id: 'sport',      label: 'Olahraga',    emoji: '⚽' },
  { id: 'emoji',      label: 'Ekspresi',    emoji: '😄' },
];

// kw = Indonesian + English keywords for search
export const STICKERS = [
  // ── Birthday 🎂 ──────────────────────────────────────────
  { id: 'birthday-cake',      themes: ['birthday', 'food'],                                    kw: ['kue', 'cake', 'ulang tahun', 'birthday'] },
  { id: 'balloon',            themes: ['birthday', 'baby', 'celebration'],                     kw: ['balon', 'balloon'] },
  { id: 'wrapped-gift',       themes: ['birthday', 'christmas', 'celebration', 'ramadan'],     kw: ['hadiah', 'kado', 'gift'] },
  { id: 'party-popper',       themes: ['birthday', 'celebration'],                             kw: ['pesta', 'konfeti', 'party', 'popper'] },
  { id: 'confetti-ball',      themes: ['birthday', 'celebration'],                             kw: ['konfeti', 'confetti', 'pesta'] },
  { id: 'candle',             themes: ['birthday', 'christmas', 'ramadan'],                    kw: ['lilin', 'candle'] },
  { id: 'trophy',             themes: ['birthday', 'graduation', 'celebration'],               kw: ['trofi', 'piala', 'trophy'] },
  { id: 'ribbon',             themes: ['birthday', 'wedding', 'christmas'],                    kw: ['pita', 'ribbon'] },
  { id: 'crown',              themes: ['birthday', 'celebration'],                             kw: ['mahkota', 'crown'] },
  { id: 'clinking-glasses',   themes: ['birthday', 'wedding', 'celebration'],                  kw: ['gelas', 'champagne', 'toast', 'minum'] },
  { id: 'sparkles',           themes: ['birthday', 'wedding', 'celebration', 'baby', 'ramadan'], kw: ['kilau', 'sparkle', 'bintang', 'glitter'] },
  { id: 'glowing-star',       themes: ['birthday', 'baby', 'celebration', 'ramadan'],         kw: ['bintang', 'star', 'berkilau'] },
  { id: 'star',               themes: ['birthday', 'baby', 'ramadan', 'celebration'],         kw: ['bintang', 'star'] },
  { id: 'partying-face',      themes: ['birthday', 'celebration', 'emoji'],                   kw: ['pesta', 'ulang tahun', 'party', 'happy'] },
  { id: 'sparkler',           themes: ['birthday', 'celebration'],                             kw: ['kembang api', 'sparkler', 'kilap'] },
  { id: 'cupcake',            themes: ['birthday', 'food'],                                    kw: ['cupcake', 'kue', 'manis'] },
  { id: 'doughnut',           themes: ['birthday', 'food'],                                    kw: ['donat', 'doughnut', 'manis'] },
  { id: 'pinata',             themes: ['birthday', 'celebration'],                             kw: ['pinata', 'pesta', 'hadiah'] },
  { id: 'cocktail-glass',     themes: ['birthday', 'celebration', 'food'],                    kw: ['koktail', 'gelas', 'cocktail', 'pesta'] },
  { id: 'shortcake',          themes: ['birthday', 'food'],                                    kw: ['kue susu', 'shortcake', 'stroberi', 'manis'] },
  { id: 'hugging-face',       themes: ['birthday', 'wedding', 'emoji'],                       kw: ['peluk', 'hug', 'sayang', 'hangat'] },

  // ── Wedding 💍 ──────────────────────────────────────────
  { id: 'ring',               themes: ['wedding', 'valentine'],                                kw: ['cincin', 'ring', 'nikah', 'kawin'] },
  { id: 'bouquet',            themes: ['wedding', 'valentine', 'nature'],                      kw: ['bunga', 'karangan', 'bouquet'] },
  { id: 'dove',               themes: ['wedding'],                                             kw: ['merpati', 'dove', 'burung', 'damai'] },
  { id: 'sparkling-heart',    themes: ['wedding', 'valentine', 'baby'],                       kw: ['hati', 'cinta', 'heart'] },
  { id: 'two-hearts',         themes: ['wedding', 'valentine'],                                kw: ['hati', 'cinta', 'heart', 'pasangan'] },
  { id: 'heart-with-ribbon',  themes: ['wedding', 'valentine'],                                kw: ['hati', 'pita', 'heart', 'hadiah'] },
  { id: 'white-flower',       themes: ['wedding', 'nature'],                                   kw: ['bunga', 'flower', 'putih', 'white'] },
  { id: 'rose',               themes: ['valentine', 'nature', 'wedding'],                      kw: ['mawar', 'rose', 'bunga'] },
  { id: 'person-in-tuxedo',   themes: ['wedding'],                                             kw: ['pengantin', 'tuxedo', 'jas', 'wedding'] },
  { id: 'gem-stone',          themes: ['valentine', 'wedding'],                                kw: ['berlian', 'diamond', 'permata', 'gem'] },
  { id: 'heart-with-arrow',   themes: ['valentine', 'wedding'],                                kw: ['hati', 'panah', 'cupid', 'cinta'] },
  { id: 'love-letter',        themes: ['valentine', 'wedding'],                                kw: ['surat', 'cinta', 'love letter', 'amplop'] },
  { id: 'cherry-blossom',     themes: ['nature', 'wedding'],                                   kw: ['bunga', 'sakura', 'cherry blossom', 'mekar'] },
  { id: 'blossom',            themes: ['nature', 'wedding'],                                   kw: ['bunga', 'blossom', 'mekar', 'cantik'] },
  { id: 'swan',               themes: ['animal', 'nature', 'wedding'],                        kw: ['angsa', 'swan', 'putih', 'elegan'] },
  { id: 'heart-hands',        themes: ['emoji', 'valentine', 'wedding'],                      kw: ['hati', 'love', 'cinta', 'heart hands'] },

  // ── Graduation 🎓 ──────────────────────────────────────
  { id: 'graduation-cap',     themes: ['graduation'],                                          kw: ['wisuda', 'toga', 'graduate', 'lulus'] },
  { id: 'scroll',             themes: ['graduation'],                                          kw: ['ijazah', 'diploma', 'scroll', 'sertifikat'] },
  { id: 'open-book',          themes: ['graduation'],                                          kw: ['buku', 'book', 'belajar', 'baca'] },
  { id: 'books',              themes: ['graduation'],                                          kw: ['buku', 'books', 'pelajaran'] },
  { id: 'medal',              themes: ['graduation', 'celebration'],                           kw: ['medali', 'medal', 'penghargaan'] },
  { id: '1st-place-medal',    themes: ['graduation', 'celebration'],                           kw: ['juara', 'pertama', 'medal', 'emas'] },
  { id: 'pencil',             themes: ['graduation'],                                          kw: ['pensil', 'pencil', 'nulis'] },
  { id: 'backpack',           themes: ['graduation'],                                          kw: ['tas', 'ransel', 'backpack', 'sekolah'] },
  { id: 'laptop',             themes: ['graduation'],                                          kw: ['laptop', 'komputer', 'computer', 'kerja'] },
  { id: 'briefcase',          themes: ['graduation'],                                          kw: ['koper', 'briefcase', 'kerja', 'kantor'] },
  { id: 'chart-increasing',   themes: ['graduation', 'celebration'],                           kw: ['grafik', 'chart', 'naik', 'sukses'] },
  { id: 'envelope',           themes: ['graduation', 'ramadan'],                               kw: ['amplop', 'envelope', 'surat'] },
  { id: 'memo',               themes: ['graduation'],                                          kw: ['memo', 'catatan', 'note'] },
  { id: 'clipboard',          themes: ['graduation'],                                          kw: ['clipboard', 'catatan', 'daftar'] },
  { id: 'desktop-computer',   themes: ['graduation'],                                          kw: ['komputer', 'desktop', 'layar', 'computer'] },
  { id: 'pen',                themes: ['graduation'],                                          kw: ['pena', 'pen', 'tulis', 'tanda tangan'] },
  { id: 'light-bulb',         themes: ['graduation', 'celebration'],                           kw: ['lampu', 'ide', 'light bulb', 'inspirasi'] },
  { id: 'magnifying-glass-tilted-right', themes: ['graduation'],                               kw: ['kaca pembesar', 'cari', 'detektif', 'penelitian'] },
  { id: 'telescope',          themes: ['graduation', 'travel', 'nature'],                      kw: ['teleskop', 'bintang', 'luar angkasa'] },
  { id: 'microscope',         themes: ['graduation'],                                          kw: ['mikroskop', 'ilmu', 'sains', 'penelitian'] },
  { id: 'test-tube',          themes: ['graduation'],                                          kw: ['tabung reaksi', 'kimia', 'sains', 'lab'] },
  { id: 'dna',                themes: ['graduation'],                                          kw: ['dna', 'biologi', 'genetika', 'sains'] },
  { id: 'abacus',             themes: ['graduation'],                                          kw: ['sempoa', 'abacus', 'hitung', 'matematika'] },
  { id: 'coin',               themes: ['graduation', 'celebration'],                           kw: ['koin', 'coin', 'uang', 'logam'] },
  { id: 'money-bag',          themes: ['graduation', 'celebration'],                           kw: ['tas uang', 'money bag', 'kaya', 'keuangan'] },
  { id: 'credit-card',        themes: ['graduation'],                                          kw: ['kartu kredit', 'credit card', 'bayar'] },
  { id: 'nerd-face',          themes: ['emoji', 'graduation'],                                kw: ['nerd', 'pintar', 'berkacamata', 'otak'] },
  { id: 'hundred-points',     themes: ['emoji', 'graduation', 'celebration'],                  kw: ['100', 'sempurna', 'perfect', 'mantap'] },
  { id: 'victory-hand',       themes: ['emoji', 'graduation', 'celebration'],                  kw: ['victory', 'menang', 'v', 'dua jari'] },
  { id: 'thumbs-up',          themes: ['emoji', 'celebration', 'graduation'],                  kw: ['jempol', 'like', 'bagus', 'oke'] },

  // ── Baby Shower 👶 ─────────────────────────────────────
  { id: 'baby-bottle',        themes: ['baby'],                                                kw: ['botol', 'susu', 'bayi', 'baby bottle'] },
  { id: 'teddy-bear',         themes: ['baby'],                                                kw: ['boneka', 'beruang', 'teddy', 'bear'] },
  { id: 'cloud',              themes: ['baby', 'nature'],                                      kw: ['awan', 'cloud', 'langit'] },
  { id: 'crescent-moon',      themes: ['baby', 'ramadan'],                                     kw: ['bulan', 'sabit', 'moon', 'malam'] },
  { id: 'rainbow',            themes: ['baby', 'nature'],                                      kw: ['pelangi', 'rainbow', 'warna'] },
  { id: 'soft-ice-cream',     themes: ['baby', 'food'],                                        kw: ['es krim', 'ice cream', 'manis'] },
  { id: 'lollipop',           themes: ['baby', 'food'],                                        kw: ['permen', 'lollipop', 'manis'] },
  { id: 'sun',                themes: ['baby', 'nature'],                                      kw: ['matahari', 'sun', 'cerah'] },
  { id: 'shooting-star',      themes: ['baby', 'celebration'],                                 kw: ['bintang jatuh', 'shooting star', 'impian'] },
  { id: 'candy',              themes: ['baby', 'food'],                                        kw: ['permen', 'candy', 'manis'] },
  { id: 'ice-cream',          themes: ['baby', 'food'],                                        kw: ['es krim', 'ice cream', 'cokelat'] },
  { id: 'cat-face',           themes: ['baby', 'animal'],                                      kw: ['kucing', 'cat', 'lucu'] },
  { id: 'dog-face',           themes: ['baby', 'animal'],                                      kw: ['anjing', 'dog', 'lucu'] },
  { id: 'rabbit-face',        themes: ['baby', 'animal'],                                      kw: ['kelinci', 'rabbit', 'bunny', 'lucu'] },
  { id: 'hatching-chick',     themes: ['baby', 'animal'],                                      kw: ['anak ayam', 'chick', 'telur', 'lucu'] },
  { id: 'duck',               themes: ['baby', 'animal'],                                      kw: ['bebek', 'duck', 'lucu'] },
  { id: 'magic-wand',         themes: ['celebration', 'baby'],                                 kw: ['tongkat sihir', 'magic', 'ajaib'] },
  { id: 'unicorn',            themes: ['animal', 'baby', 'celebration'],                       kw: ['unicorn', 'tanduk', 'ajaib', 'warna-warni'] },
  { id: 'smiling-face-with-halo', themes: ['emoji', 'baby'],                                  kw: ['malaikat', 'halo', 'angel', 'suci'] },
  { id: 'glass-of-milk',      themes: ['food', 'baby'],                                        kw: ['susu', 'milk', 'minum', 'sehat'] },
  { id: 'night-with-stars',   themes: ['travel', 'nature', 'baby'],                           kw: ['malam', 'bintang', 'langit', 'malam hari'] },

  // ── Valentine ❤️ ──────────────────────────────────────
  { id: 'red-heart',          themes: ['valentine'],                                           kw: ['hati', 'cinta', 'love', 'heart'] },
  { id: 'revolving-hearts',   themes: ['valentine'],                                           kw: ['hati', 'cinta', 'heart', 'putar'] },
  { id: 'kiss-mark',          themes: ['valentine'],                                           kw: ['ciuman', 'bibir', 'kiss', 'cinta'] },
  { id: 'smiling-face-with-hearts', themes: ['valentine'],                                     kw: ['hati', 'bahagia', 'cinta', 'senyum'] },
  { id: 'lipstick',           themes: ['valentine'],                                           kw: ['lipstik', 'lipstick', 'make up'] },
  { id: 'chocolate-bar',      themes: ['valentine', 'food'],                                   kw: ['cokelat', 'chocolate', 'manis', 'hadiah'] },
  { id: 'wine-glass',         themes: ['valentine', 'food'],                                   kw: ['anggur', 'wine', 'gelas', 'romantis'] },
  { id: 'beating-heart',      themes: ['valentine'],                                           kw: ['hati', 'cinta', 'berdenyut'] },
  { id: 'growing-heart',      themes: ['valentine'],                                           kw: ['hati', 'cinta', 'tumbuh'] },
  { id: 'heart-on-fire',      themes: ['valentine'],                                           kw: ['hati', 'cinta', 'api', 'passion'] },
  { id: 'strawberry',         themes: ['valentine', 'food', 'nature'],                        kw: ['stroberi', 'strawberry', 'buah', 'merah'] },
  { id: 'cherries',           themes: ['valentine', 'food', 'nature'],                        kw: ['ceri', 'cherries', 'buah', 'merah'] },
  { id: 'winking-face',       themes: ['emoji', 'valentine'],                                  kw: ['kedip', 'wink', 'goda', 'nakal'] },
  { id: 'smiling-face-with-heart-eyes', themes: ['emoji', 'valentine'],                       kw: ['suka', 'cinta', 'heart eyes', 'love'] },
  { id: 'kissing-face',       themes: ['emoji', 'valentine'],                                  kw: ['ciuman', 'kiss', 'sayang', 'cinta'] },
  { id: 'face-blowing-a-kiss',themes: ['emoji', 'valentine'],                                  kw: ['ciuman', 'kiss', 'cinta', 'sayang'] },

  // ── Ramadan 🌙 ─────────────────────────────────────────
  { id: 'star-and-crescent',  themes: ['ramadan'],                                             kw: ['islam', 'bulan bintang', 'ramadan', 'islami'] },
  { id: 'mosque',             themes: ['ramadan'],                                             kw: ['masjid', 'mosque', 'sholat'] },
  { id: 'diya-lamp',          themes: ['ramadan'],                                             kw: ['lampu', 'lentera', 'lamp', 'cahaya'] },
  { id: 'prayer-beads',       themes: ['ramadan'],                                             kw: ['tasbih', 'prayer', 'dzikir'] },
  { id: 'hot-beverage',       themes: ['ramadan', 'food'],                                     kw: ['kopi', 'teh', 'minuman', 'hangat', 'coffee'] },
  { id: 'teacup-without-handle', themes: ['ramadan', 'food'],                                  kw: ['teh', 'tea', 'minum', 'hangat'] },
  { id: 'pot-of-food',        themes: ['ramadan', 'food'],                                     kw: ['masakan', 'makanan', 'pot', 'food'] },
  { id: 'lantern',            themes: ['ramadan'],                                             kw: ['lentera', 'lampion', 'lantern', 'cahaya'] },
  { id: 'red-envelope',       themes: ['christmas', 'ramadan'],                                kw: ['amplop merah', 'red envelope', 'angpaw', 'hadiah'] },
  { id: 'firecracker',        themes: ['celebration', 'ramadan'],                              kw: ['petasan', 'firecracker', 'meriah'] },
  { id: 'lotus',              themes: ['nature', 'ramadan'],                                   kw: ['teratai', 'lotus', 'bunga', 'suci'] },
  { id: 'folded-hands',       themes: ['emoji', 'ramadan'],                                    kw: ['doa', 'pray', 'tolong', 'terima kasih'] },
  { id: 'teapot',             themes: ['food', 'ramadan'],                                     kw: ['teko', 'teapot', 'teh', 'menyeduh'] },

  // ── Nature 🌸 ──────────────────────────────────────────
  { id: 'sunflower',          themes: ['nature'],                                              kw: ['bunga matahari', 'sunflower', 'kuning'] },
  { id: 'hibiscus',           themes: ['nature', 'wedding'],                                   kw: ['bunga', 'hibiscus', 'merah'] },
  { id: 'tulip',              themes: ['nature', 'wedding'],                                   kw: ['tulip', 'bunga', 'cantik'] },
  { id: 'butterfly',          themes: ['nature', 'animal', 'baby'],                           kw: ['kupu-kupu', 'butterfly', 'terbang'] },
  { id: 'four-leaf-clover',   themes: ['nature'],                                              kw: ['semanggi', 'clover', 'hoki', 'luck'] },
  { id: 'leaf-fluttering-in-wind', themes: ['nature'],                                        kw: ['daun', 'leaf', 'hijau', 'angin'] },
  { id: 'seedling',           themes: ['nature'],                                              kw: ['bibit', 'tanaman', 'tumbuh', 'seedling'] },
  { id: 'herb',               themes: ['nature'],                                              kw: ['daun', 'herb', 'herbal', 'hijau'] },
  { id: 'mushroom',           themes: ['nature'],                                              kw: ['jamur', 'mushroom', 'merah'] },
  { id: 'deciduous-tree',     themes: ['nature'],                                              kw: ['pohon', 'tree', 'hijau', 'hutan'] },
  { id: 'droplet',            themes: ['nature'],                                              kw: ['tetes', 'air', 'droplet', 'hujan'] },
  { id: 'water-wave',         themes: ['nature'],                                              kw: ['ombak', 'laut', 'wave', 'air'] },
  { id: 'cactus',             themes: ['nature'],                                              kw: ['kaktus', 'cactus', 'gurun'] },
  { id: 'palm-tree',          themes: ['nature', 'travel'],                                    kw: ['pohon palem', 'palm tree', 'pantai', 'tropis'] },
  { id: 'evergreen-tree',     themes: ['nature', 'christmas'],                                 kw: ['pohon pinus', 'evergreen', 'hijau', 'pine'] },
  { id: 'snowflake',          themes: ['nature', 'christmas'],                                 kw: ['salju', 'snowflake', 'dingin', 'snow'] },
  { id: 'fish',               themes: ['nature', 'animal'],                                    kw: ['ikan', 'fish', 'laut'] },
  { id: 'tropical-fish',      themes: ['nature', 'animal'],                                    kw: ['ikan tropis', 'tropical fish', 'warna'] },
  { id: 'frog',               themes: ['nature', 'animal', 'baby'],                           kw: ['katak', 'frog', 'hijau', 'lucu'] },
  { id: 'turtle',             themes: ['nature', 'animal', 'baby'],                           kw: ['kura-kura', 'turtle', 'lambat'] },
  { id: 'snail',              themes: ['nature', 'animal'],                                    kw: ['siput', 'snail', 'lambat'] },
  { id: 'honeybee',           themes: ['nature', 'animal'],                                    kw: ['lebah', 'bee', 'madu', 'honey'] },
  { id: 'lady-beetle',        themes: ['nature', 'animal'],                                    kw: ['kumbang', 'ladybug', 'merah', 'bintik'] },
  { id: 'ant',                themes: ['nature', 'animal'],                                    kw: ['semut', 'ant', 'kerja keras'] },
  { id: 'maple-leaf',         themes: ['nature'],                                              kw: ['daun maple', 'maple leaf', 'merah', 'gugur'] },
  { id: 'fallen-leaf',        themes: ['nature'],                                              kw: ['daun gugur', 'fallen leaf', 'musim gugur'] },
  { id: 'wilted-flower',      themes: ['nature'],                                              kw: ['bunga layu', 'wilted', 'sedih'] },
  { id: 'potted-plant',       themes: ['nature'],                                              kw: ['tanaman pot', 'pot', 'indoor', 'hiasan'] },
  { id: 'shamrock',           themes: ['nature'],                                              kw: ['semanggi', 'shamrock', 'hijau', 'luck'] },
  { id: 'wind-chime',         themes: ['celebration', 'nature'],                               kw: ['lonceng angin', 'wind chime', 'dekorasi'] },
  { id: 'camping',            themes: ['travel', 'nature'],                                    kw: ['berkemah', 'camping', 'alam', 'tenda'] },
  { id: 'national-park',      themes: ['travel', 'nature'],                                    kw: ['taman nasional', 'alam', 'wisata', 'park'] },
  { id: 'desert-island',      themes: ['travel', 'nature'],                                    kw: ['pulau', 'island', 'pantai', 'tropis'] },

  // ── Animal 🐱 ──────────────────────────────────────────
  { id: 'bear',               themes: ['animal'],                                              kw: ['beruang', 'bear', 'lucu'] },
  { id: 'panda-face',         themes: ['animal'],                                              kw: ['panda', 'lucu', 'hitam putih'] },
  { id: 'koala',              themes: ['animal'],                                              kw: ['koala', 'australia', 'lucu'] },
  { id: 'tiger-face',         themes: ['animal'],                                              kw: ['harimau', 'tiger', 'ganas'] },
  { id: 'lion-face',          themes: ['animal'],                                              kw: ['singa', 'lion', 'raja'] },
  { id: 'hamster',            themes: ['animal'],                                              kw: ['hamster', 'tikus', 'lucu'] },
  { id: 'mouse-face',         themes: ['animal'],                                              kw: ['tikus', 'mouse', 'kecil', 'lucu'] },
  { id: 'owl',                themes: ['animal', 'graduation'],                                kw: ['burung hantu', 'owl', 'pintar', 'malam'] },
  { id: 'penguin',            themes: ['animal'],                                              kw: ['penguin', 'hitam putih', 'dingin'] },
  { id: 'fox-face',           themes: ['animal'],                                              kw: ['rubah', 'fox', 'oranye', 'cerdik'] },
  { id: 'elephant',           themes: ['animal'],                                              kw: ['gajah', 'elephant', 'besar'] },
  { id: 'pig-face',           themes: ['animal'],                                              kw: ['babi', 'pig', 'pink', 'lucu'] },
  { id: 'horse-face',         themes: ['animal'],                                              kw: ['kuda', 'horse', 'berlari'] },
  { id: 'monkey-face',        themes: ['animal'],                                              kw: ['monyet', 'monkey', 'lucu'] },
  { id: 'dolphin',            themes: ['animal', 'travel', 'nature'],                         kw: ['lumba-lumba', 'dolphin', 'laut'] },
  { id: 'baby-chick',         themes: ['animal', 'baby'],                                      kw: ['anak ayam', 'chick', 'kuning', 'lucu'] },
  { id: 'cow-face',           themes: ['animal'],                                              kw: ['sapi', 'cow', 'susu', 'lucu'] },
  { id: 'wolf',               themes: ['animal'],                                              kw: ['serigala', 'wolf', 'liar'] },
  { id: 'gorilla',            themes: ['animal'],                                              kw: ['gorila', 'gorilla', 'besar', 'kuat'] },
  { id: 'crocodile',          themes: ['animal'],                                              kw: ['buaya', 'crocodile', 'hijau', 'ganas'] },
  { id: 'parrot',             themes: ['animal'],                                              kw: ['beo', 'parrot', 'warna', 'burung'] },
  { id: 'flamingo',           themes: ['animal', 'nature'],                                    kw: ['flamingo', 'burung', 'pink', 'cantik'] },
  { id: 'peacock',            themes: ['animal', 'nature'],                                    kw: ['merak', 'peacock', 'warna-warni', 'indah'] },
  { id: 'eagle',              themes: ['animal', 'nature'],                                    kw: ['elang', 'eagle', 'terbang', 'gagah'] },
  { id: 'hedgehog',           themes: ['animal', 'baby'],                                      kw: ['landak', 'hedgehog', 'lucu', 'duri'] },
  { id: 'beaver',             themes: ['animal', 'nature'],                                    kw: ['berang-berang', 'beaver', 'lucu'] },
  { id: 'otter',              themes: ['animal', 'nature'],                                    kw: ['berang-berang laut', 'otter', 'lucu', 'air'] },
  { id: 'sloth',              themes: ['animal'],                                              kw: ['kukang', 'sloth', 'lambat', 'lucu'] },
  { id: 'raccoon',            themes: ['animal'],                                              kw: ['rakun', 'raccoon', 'hitam', 'imut'] },
  { id: 'seal',               themes: ['animal', 'nature'],                                    kw: ['anjing laut', 'seal', 'gemuk', 'lucu'] },
  { id: 'shark',              themes: ['animal', 'nature'],                                    kw: ['hiu', 'shark', 'laut', 'ganas'] },
  { id: 'octopus',            themes: ['animal', 'nature'],                                    kw: ['gurita', 'octopus', 'laut', 'tentakel'] },
  { id: 'jellyfish',          themes: ['animal', 'nature'],                                    kw: ['ubur-ubur', 'jellyfish', 'laut'] },
  { id: 'blowfish',           themes: ['animal', 'nature'],                                    kw: ['ikan buntal', 'blowfish', 'duri', 'laut'] },
  { id: 'coral',              themes: ['animal', 'nature'],                                    kw: ['terumbu karang', 'coral', 'laut', 'bawah laut'] },
  { id: 'spiral-shell',       themes: ['animal', 'nature', 'travel'],                         kw: ['cangkang', 'kerang', 'shell', 'pantai'] },
  { id: 'spouting-whale',     themes: ['animal', 'nature'],                                    kw: ['paus', 'whale', 'semburan', 'laut'] },
  { id: 'dragon',             themes: ['animal', 'celebration'],                               kw: ['naga', 'dragon', 'api', 'mitologi'] },
  { id: 'phoenix-bird',       themes: ['animal', 'celebration'],                               kw: ['phoenix', 'api', 'terbang', 'mitos'] },
  { id: 'water-buffalo',      themes: ['animal', 'nature'],                                    kw: ['kerbau', 'water buffalo', 'sawah'] },
  { id: 'rooster',            themes: ['animal', 'nature'],                                    kw: ['ayam jago', 'rooster', 'pagi', 'berkokok'] },
  { id: 'kangaroo',           themes: ['animal'],                                              kw: ['kangguru', 'kangaroo', 'australia', 'lompat'] },
  { id: 'llama',              themes: ['animal'],                                              kw: ['llama', 'bulu', 'lucu', 'peru'] },
  { id: 'hippopotamus',       themes: ['animal'],                                              kw: ['kuda nil', 'hippo', 'besar', 'air'] },
  { id: 'rhinoceros',         themes: ['animal'],                                              kw: ['badak', 'rhinoceros', 'tanduk', 'besar'] },
  { id: 'zebra',              themes: ['animal', 'nature'],                                    kw: ['zebra', 'hitam putih', 'belang', 'africa'] },
  { id: 'giraffe',            themes: ['animal'],                                              kw: ['jerapah', 'giraffe', 'panjang', 'bintik'] },
  { id: 'camel',              themes: ['animal', 'travel'],                                    kw: ['unta', 'camel', 'gurun', 'gubal'] },
  { id: 'goat',               themes: ['animal', 'nature'],                                    kw: ['kambing', 'goat', 'tanduk', 'lucu'] },
  { id: 'pig',                themes: ['animal'],                                              kw: ['babi', 'pig', 'pink', 'gemuk'] },
  { id: 'chicken',            themes: ['animal', 'food'],                                      kw: ['ayam', 'chicken', 'berkokok', 'telur'] },

  // ── Celebration 🎉 ─────────────────────────────────────
  { id: 'fireworks',          themes: ['celebration', 'christmas'],                            kw: ['kembang api', 'fireworks', 'malam'] },
  { id: 'camera',             themes: ['celebration', 'travel'],                               kw: ['kamera', 'foto', 'camera', 'shoot'] },
  { id: 'camera-with-flash',  themes: ['celebration', 'travel'],                               kw: ['kamera', 'foto', 'flash', 'kilat'] },
  { id: 'film-frames',        themes: ['celebration', 'travel'],                               kw: ['film', 'foto', 'kenangan', 'memories'] },
  { id: 'dizzy',              themes: ['celebration', 'emoji'],                                kw: ['kilau', 'bintang', 'sparkle', 'pusing'] },
  { id: 'clapping-hands',     themes: ['celebration', 'emoji', 'graduation'],                  kw: ['tepuk tangan', 'clap', 'bravo', 'applause'] },
  { id: 'raising-hands',      themes: ['celebration', 'emoji'],                                kw: ['angkat tangan', 'hore', 'celebrate', 'yeay'] },
  { id: 'woman-dancing',      themes: ['celebration', 'music'],                                kw: ['menari', 'dance', 'pesta'] },
  { id: 'man-dancing',        themes: ['celebration', 'music'],                                kw: ['menari', 'dance', 'disco'] },
  { id: 'rocket',             themes: ['celebration', 'travel'],                               kw: ['roket', 'rocket', 'luar angkasa', 'space'] },
  { id: 'jack-o-lantern',     themes: ['celebration'],                                         kw: ['labu', 'halloween', 'seram', 'kuning'] },
  { id: 'mirror-ball',        themes: ['celebration', 'music'],                                kw: ['disko', 'mirror ball', 'pesta', 'kilap'] },
  { id: 'admission-tickets',  themes: ['celebration', 'travel'],                               kw: ['tiket', 'masuk', 'konser', 'acara'] },
  { id: 'ticket',             themes: ['celebration', 'travel'],                               kw: ['tiket', 'karcis', 'masuk'] },
  { id: 'crystal-ball',       themes: ['celebration'],                                         kw: ['bola kristal', 'ramalan', 'sihir'] },
  { id: 'nesting-dolls',      themes: ['celebration'],                                         kw: ['boneka rusia', 'matryoshka', 'koleksi'] },
  { id: 'performing-arts',    themes: ['celebration', 'music'],                                kw: ['pertunjukan', 'teater', 'seni', 'drama'] },
  { id: 'framed-picture',     themes: ['celebration', 'travel'],                               kw: ['foto', 'bingkai', 'gambar', 'kenangan'] },
  { id: 'artist-palette',     themes: ['celebration'],                                         kw: ['palet', 'lukis', 'seni', 'warna', 'art'] },
  { id: 'slot-machine',       themes: ['celebration', 'travel'],                               kw: ['mesin slot', 'kasino', 'jackpot'] },
  { id: 'fire',               themes: ['celebration', 'nature', 'emoji'],                     kw: ['api', 'fire', 'panas', 'hot', 'keren'] },
  { id: 'collision',          themes: ['celebration', 'emoji'],                                kw: ['ledak', 'boom', 'pow', 'dahsyat'] },

  // ── Christmas 🎄 ──────────────────────────────────────
  { id: 'christmas-tree',     themes: ['christmas'],                                           kw: ['pohon natal', 'christmas tree', 'natal'] },
  { id: 'bell',               themes: ['christmas'],                                           kw: ['bel', 'lonceng', 'bell', 'natal'] },
  { id: 'santa-claus',        themes: ['christmas'],                                           kw: ['santa', 'natal', 'christmas', 'hadiah'] },
  { id: 'snowman',            themes: ['christmas'],                                           kw: ['manusia salju', 'snowman', 'dingin'] },
  { id: 'snowman-without-snow',themes: ['christmas'],                                          kw: ['manusia salju', 'snowman', 'dingin'] },
  { id: 'deer',               themes: ['christmas', 'animal'],                                 kw: ['rusa', 'deer', 'natal', 'christmas'] },
  { id: 'socks',              themes: ['christmas'],                                           kw: ['kaus kaki', 'socks', 'natal', 'hadiah'] },
  { id: 'pine-decoration',    themes: ['christmas'],                                           kw: ['dekorasi', 'ornamen', 'natal'] },
  { id: 'gloves',             themes: ['christmas'],                                           kw: ['sarung tangan', 'gloves', 'dingin'] },
  { id: 'snow-capped-mountain',themes: ['travel', 'nature', 'christmas'],                      kw: ['gunung salju', 'mountain', 'salju'] },

  // ── Food 🍰 ──────────────────────────────────────────
  { id: 'pizza',              themes: ['food'],                                                kw: ['pizza', 'keju', 'cheese', 'makan'] },
  { id: 'hamburger',          themes: ['food'],                                                kw: ['hamburger', 'burger', 'cepat saji'] },
  { id: 'hot-dog',            themes: ['food'],                                                kw: ['hot dog', 'sosis', 'sausage'] },
  { id: 'sushi',              themes: ['food'],                                                kw: ['sushi', 'jepang', 'japanese', 'ikan'] },
  { id: 'bento-box',          themes: ['food'],                                                kw: ['bento', 'nasi', 'bekal', 'makan siang'] },
  { id: 'rice-ball',          themes: ['food'],                                                kw: ['onigiri', 'nasi', 'rice ball', 'jepang'] },
  { id: 'steaming-bowl',      themes: ['food'],                                                kw: ['mi', 'mie', 'noodle', 'kuah', 'bowl'] },
  { id: 'green-salad',        themes: ['food'],                                                kw: ['salad', 'sayur', 'sehat', 'hijau'] },
  { id: 'broccoli',           themes: ['food', 'nature'],                                      kw: ['brokoli', 'broccoli', 'sayur', 'sehat'] },
  { id: 'tomato',             themes: ['food', 'nature'],                                      kw: ['tomat', 'tomato', 'merah', 'segar'] },
  { id: 'watermelon',         themes: ['food', 'nature'],                                      kw: ['semangka', 'watermelon', 'merah', 'segar'] },
  { id: 'pineapple',          themes: ['food', 'nature'],                                      kw: ['nanas', 'pineapple', 'kuning', 'tropis'] },
  { id: 'mango',              themes: ['food', 'nature'],                                      kw: ['mangga', 'mango', 'kuning', 'tropis'] },
  { id: 'grapes',             themes: ['food', 'nature'],                                      kw: ['anggur', 'grapes', 'ungu', 'buah'] },
  { id: 'lemon',              themes: ['food', 'nature'],                                      kw: ['lemon', 'jeruk', 'kuning', 'asam'] },
  { id: 'coconut',            themes: ['food', 'nature', 'travel'],                           kw: ['kelapa', 'coconut', 'tropis', 'pantai'] },
  { id: 'croissant',          themes: ['food'],                                                kw: ['croissant', 'roti', 'prancis', 'sarapan'] },
  { id: 'cookie',             themes: ['food'],                                                kw: ['kue kering', 'cookie', 'biskuit', 'manis'] },
  { id: 'honey-pot',          themes: ['food', 'nature'],                                      kw: ['madu', 'honey', 'manis', 'lebah'] },
  { id: 'cup-with-straw',     themes: ['food'],                                                kw: ['minuman', 'gelas', 'sedotan', 'soda'] },
  { id: 'tropical-drink',     themes: ['food', 'travel'],                                      kw: ['minuman tropis', 'cocktail', 'segar', 'holiday'] },
  { id: 'fried-egg',          themes: ['food'],                                                kw: ['telur', 'fried egg', 'sarapan', 'dadar'] },
  { id: 'baguette-bread',     themes: ['food'],                                                kw: ['roti', 'baguette', 'prancis', 'sarapan'] },
  { id: 'cheese-wedge',       themes: ['food'],                                                kw: ['keju', 'cheese', 'kuning'] },
  { id: 'corn',               themes: ['food', 'nature'],                                      kw: ['jagung', 'corn', 'kuning', 'sayur'] },
  { id: 'peach',              themes: ['food', 'nature'],                                      kw: ['peach', 'persik', 'buah', 'merah muda'] },
  { id: 'avocado',            themes: ['food', 'nature'],                                      kw: ['alpukat', 'avocado', 'hijau', 'sehat'] },
  { id: 'pancakes',           themes: ['food'],                                                kw: ['pancake', 'sarapan', 'manis', 'madu'] },
  { id: 'taco',               themes: ['food'],                                                kw: ['taco', 'meksiko', 'mexican', 'makanan'] },
  { id: 'burrito',            themes: ['food'],                                                kw: ['burrito', 'meksiko', 'nasi bungkus'] },
  { id: 'spaghetti',          themes: ['food'],                                                kw: ['mie', 'spaghetti', 'pasta', 'italia'] },
  { id: 'curry-rice',         themes: ['food'],                                                kw: ['kari', 'curry', 'nasi', 'india'] },
  { id: 'waffle',             themes: ['food'],                                                kw: ['waffle', 'roti', 'sarapan', 'manis'] },
  { id: 'pie',                themes: ['food'],                                                kw: ['pai', 'pie', 'kue', 'buah'] },
  { id: 'bubble-tea',         themes: ['food'],                                                kw: ['boba', 'bubble tea', 'minuman', 'tapioca'] },
  { id: 'beer-mug',           themes: ['food', 'celebration'],                                 kw: ['bir', 'beer', 'mug', 'minuman'] },
  { id: 'clinking-beer-mugs', themes: ['food', 'celebration'],                                 kw: ['cheers', 'bir', 'beer', 'minum bersama'] },
  { id: 'bottle-with-popping-cork', themes: ['food', 'celebration'],                           kw: ['champagne', 'botol', 'pesta', 'meledak'] },
  { id: 'bacon',              themes: ['food'],                                                kw: ['bacon', 'daging', 'sarapan', 'goreng'] },
  { id: 'dumpling',           themes: ['food'],                                                kw: ['dimsum', 'dumpling', 'siomay', 'cina'] },
  { id: 'fried-shrimp',       themes: ['food'],                                                kw: ['udang goreng', 'tempura', 'udang'] },
  { id: 'popcorn',            themes: ['food', 'celebration'],                                 kw: ['popcorn', 'bioskop', 'jagung', 'nonton'] },
  { id: 'sandwich',           themes: ['food'],                                                kw: ['sandwich', 'roti', 'makan siang'] },
  { id: 'green-apple',        themes: ['food', 'nature'],                                      kw: ['apel hijau', 'green apple', 'buah', 'sehat'] },
  { id: 'banana',             themes: ['food', 'nature', 'animal'],                           kw: ['pisang', 'banana', 'buah', 'kuning'] },
  { id: 'melon',              themes: ['food', 'nature'],                                      kw: ['melon', 'buah', 'hijau', 'segar'] },
  { id: 'blueberries',        themes: ['food', 'nature'],                                      kw: ['blueberry', 'ungu', 'buah', 'sehat'] },
  { id: 'kiwi-fruit',         themes: ['food', 'nature'],                                      kw: ['kiwi', 'buah', 'hijau', 'segar'] },
  { id: 'tangerine',          themes: ['food', 'nature'],                                      kw: ['jeruk', 'tangerine', 'orange', 'buah'] },
  { id: 'pear',               themes: ['food', 'nature'],                                      kw: ['pir', 'pear', 'buah', 'hijau'] },
  { id: 'french-fries',       themes: ['food'],                                                kw: ['kentang goreng', 'french fries', 'crispy'] },
  { id: 'salt',               themes: ['food'],                                                kw: ['garam', 'salt', 'bumbu', 'masak'] },
  { id: 'tumbler-glass',      themes: ['food'],                                                kw: ['gelas', 'minum', 'tumbler', 'minuman'] },
  { id: 'face-savoring-food', themes: ['emoji', 'food'],                                       kw: ['yummy', 'enak', 'makanan', 'lezat'] },

  // ── Travel ✈️ ──────────────────────────────────────────
  { id: 'airplane',           themes: ['travel'],                                              kw: ['pesawat', 'airplane', 'terbang', 'liburan'] },
  { id: 'helicopter',         themes: ['travel'],                                              kw: ['helikopter', 'helicopter', 'terbang'] },
  { id: 'automobile',         themes: ['travel'],                                              kw: ['mobil', 'car', 'kendaraan', 'jalan'] },
  { id: 'bus',                themes: ['travel'],                                              kw: ['bus', 'angkutan', 'umum', 'kota'] },
  { id: 'bicycle',            themes: ['travel'],                                              kw: ['sepeda', 'bicycle', 'bike', 'sehat'] },
  { id: 'motor-scooter',      themes: ['travel'],                                              kw: ['motor', 'scooter', 'ojek', 'skuter'] },
  { id: 'sailboat',           themes: ['travel', 'nature'],                                    kw: ['perahu layar', 'sailboat', 'laut', 'angin'] },
  { id: 'speedboat',          themes: ['travel'],                                              kw: ['speedboat', 'kapal cepat', 'laut'] },
  { id: 'globe-showing-asia-australia', themes: ['travel'],                                    kw: ['bumi', 'earth', 'globe', 'dunia', 'asia'] },
  { id: 'world-map',          themes: ['travel'],                                              kw: ['peta', 'map', 'dunia', 'perjalanan'] },
  { id: 'luggage',            themes: ['travel'],                                              kw: ['koper', 'luggage', 'liburan', 'packing'] },
  { id: 'sunglasses',         themes: ['travel'],                                              kw: ['kacamata', 'sunglasses', 'pantai', 'cool'] },
  { id: 'beach-with-umbrella',themes: ['travel', 'nature'],                                    kw: ['pantai', 'beach', 'liburan', 'laut'] },
  { id: 'mount-fuji',         themes: ['travel'],                                              kw: ['gunung', 'fuji', 'jepang', 'mountain'] },
  { id: 'sunrise',            themes: ['travel', 'nature'],                                    kw: ['matahari terbit', 'sunrise', 'pagi', 'indah'] },
  { id: 'compass',            themes: ['travel'],                                              kw: ['kompas', 'compass', 'arah', 'petualangan'] },
  { id: 'tent',               themes: ['travel', 'nature'],                                    kw: ['tenda', 'tent', 'camping', 'alam'] },
  { id: 'moai',               themes: ['travel'],                                              kw: ['patung', 'moai', 'easter island', 'wisata'] },
  { id: 'tokyo-tower',        themes: ['travel'],                                              kw: ['menara', 'tokyo', 'jepang', 'wisata'] },
  { id: 'statue-of-liberty',  themes: ['travel'],                                              kw: ['patung liberty', 'new york', 'wisata', 'usa'] },
  { id: 'ferris-wheel',       themes: ['travel', 'celebration'],                               kw: ['bianglala', 'ferris wheel', 'taman', 'wisata'] },
  { id: 'roller-coaster',     themes: ['travel', 'celebration'],                               kw: ['wahana', 'roller coaster', 'taman', 'seru'] },
  { id: 'cityscape',          themes: ['travel'],                                              kw: ['kota', 'city', 'gedung', 'urban'] },
  { id: 'bridge-at-night',    themes: ['travel'],                                              kw: ['jembatan', 'malam', 'kota', 'lampu'] },
  { id: 'sunrise-over-mountains', themes: ['travel', 'nature'],                                kw: ['matahari terbit', 'gunung', 'sunrise', 'pagi'] },
  { id: 'hot-springs',        themes: ['travel'],                                              kw: ['pemandian panas', 'hot spring', 'relax', 'onsen'] },
  { id: 'foggy',              themes: ['travel', 'nature'],                                    kw: ['berkabut', 'foggy', 'misty', 'dingin'] },
  { id: 'volcano',            themes: ['travel', 'nature'],                                    kw: ['gunung berapi', 'volcano', 'letusan'] },
  { id: 'racing-car',         themes: ['travel', 'sport'],                                     kw: ['mobil balap', 'racing', 'cepat', 'f1'] },
  { id: 'motorcycle',         themes: ['travel'],                                              kw: ['motor', 'motorcycle', 'besar', 'touring'] },
  { id: 'canoe',              themes: ['travel', 'sport', 'nature'],                          kw: ['kano', 'canoe', 'dayung', 'sungai'] },
  { id: 'anchor',             themes: ['travel', 'nature'],                                    kw: ['jangkar', 'anchor', 'kapal', 'laut'] },
  { id: 'hindu-temple',       themes: ['travel'],                                              kw: ['pura', 'candi', 'temple', 'wisata', 'bali'] },
  { id: 'smiling-face-with-sunglasses', themes: ['emoji', 'travel'],                          kw: ['keren', 'cool', 'kacamata', 'sunglass'] },
  { id: 'cowboy-hat-face',    themes: ['emoji', 'travel'],                                     kw: ['cowboy', 'topi', 'western', 'koboi'] },

  // ── Music 🎵 ──────────────────────────────────────────
  { id: 'musical-note',       themes: ['music', 'celebration'],                                kw: ['nada', 'musik', 'music', 'note'] },
  { id: 'musical-notes',      themes: ['music', 'celebration'],                                kw: ['nada', 'musik', 'music', 'lagu'] },
  { id: 'guitar',             themes: ['music', 'celebration'],                                kw: ['gitar', 'guitar', 'musik', 'petik'] },
  { id: 'microphone',         themes: ['music', 'celebration'],                                kw: ['mikrofon', 'microphone', 'nyanyi', 'sing'] },
  { id: 'headphone',          themes: ['music', 'celebration'],                                kw: ['headphone', 'musik', 'dengar', 'music'] },
  { id: 'saxophone',          themes: ['music'],                                               kw: ['saksofon', 'saxophone', 'jazz', 'musik'] },
  { id: 'drum',               themes: ['music'],                                               kw: ['drum', 'perkusi', 'ketuk', 'musik'] },
  { id: 'violin',             themes: ['music'],                                               kw: ['biola', 'violin', 'gesek', 'klasik'] },
  { id: 'trumpet',            themes: ['music'],                                               kw: ['terompet', 'trumpet', 'tiup', 'musik'] },
  { id: 'banjo',              themes: ['music'],                                               kw: ['banjo', 'petik', 'folk', 'musik'] },
  { id: 'musical-keyboard',   themes: ['music'],                                               kw: ['keyboard', 'piano', 'tuts', 'musik'] },
  { id: 'radio',              themes: ['music'],                                               kw: ['radio', 'siaran', 'musik', 'lagu'] },
  { id: 'studio-microphone',  themes: ['music'],                                               kw: ['mikrofon studio', 'recording', 'rekam'] },
  { id: 'musical-score',      themes: ['music'],                                               kw: ['not balok', 'partitur', 'musik', 'klasik'] },
  { id: 'long-drum',          themes: ['music'],                                               kw: ['kendang', 'gendang', 'drum', 'tradisional'] },
  { id: 'accordion',          themes: ['music'],                                               kw: ['akordeon', 'accordion', 'musik', 'tiup'] },
  { id: 'flute',              themes: ['music'],                                               kw: ['seruling', 'flute', 'tiup', 'musik'] },
  { id: 'maracas',            themes: ['music', 'celebration'],                                kw: ['marakas', 'maracas', 'goyang', 'latin'] },
  { id: 'clapper-board',      themes: ['music', 'celebration'],                                kw: ['clapperboard', 'film', 'produksi', 'aksi'] },

  // ── Sport ⚽ ──────────────────────────────────────────
  { id: 'soccer-ball',        themes: ['sport'],                                               kw: ['bola', 'sepak bola', 'football', 'soccer'] },
  { id: 'basketball',         themes: ['sport'],                                               kw: ['basket', 'basketball', 'bola'] },
  { id: 'baseball',           themes: ['sport'],                                               kw: ['baseball', 'bola', 'pemukul'] },
  { id: 'volleyball',         themes: ['sport'],                                               kw: ['voli', 'volleyball', 'bola'] },
  { id: 'rugby-football',     themes: ['sport'],                                               kw: ['rugby', 'bola', 'olahraga'] },
  { id: 'tennis',             themes: ['sport'],                                               kw: ['tenis', 'tennis', 'raket'] },
  { id: 'badminton',          themes: ['sport'],                                               kw: ['bulu tangkis', 'badminton', 'raket'] },
  { id: 'ping-pong',          themes: ['sport'],                                               kw: ['tenis meja', 'ping pong', 'raket'] },
  { id: 'boxing-glove',       themes: ['sport'],                                               kw: ['tinju', 'boxing', 'glove'] },
  { id: 'martial-arts-uniform',themes: ['sport'],                                              kw: ['bela diri', 'karate', 'judo', 'martial arts'] },
  { id: 'ice-skate',          themes: ['sport', 'christmas'],                                  kw: ['sepatu es', 'ice skate', 'dingin'] },
  { id: 'fishing-pole',       themes: ['sport', 'nature'],                                     kw: ['pancing', 'fishing', 'ikan'] },
  { id: 'diving-mask',        themes: ['sport', 'travel'],                                     kw: ['menyelam', 'diving', 'snorkel', 'laut'] },
  { id: 'skis',               themes: ['sport', 'christmas'],                                  kw: ['ski', 'salju', 'olahraga', 'snow'] },
  { id: 'sled',               themes: ['sport', 'christmas'],                                  kw: ['kereta salju', 'sled', 'dingin', 'snow'] },
  { id: 'bullseye',           themes: ['sport'],                                               kw: ['target', 'panah', 'bullseye', 'tepat'] },
  { id: 'flag-in-hole',       themes: ['sport'],                                               kw: ['golf', 'hole', 'bendera', 'lapangan'] },
  { id: 'american-football',  themes: ['sport'],                                               kw: ['american football', 'bola', 'olahraga'] },
  { id: 'flying-disc',        themes: ['sport', 'travel'],                                     kw: ['frisbee', 'disc', 'lempar'] },
  { id: 'cricket-game',       themes: ['sport'],                                               kw: ['kriket', 'cricket', 'olahraga'] },
  { id: 'bowling',            themes: ['sport'],                                               kw: ['bowling', 'bola', 'pin'] },
  { id: 'kite',               themes: ['sport', 'celebration', 'nature'],                     kw: ['layang-layang', 'kite', 'terbang', 'angin'] },
  { id: 'skateboard',         themes: ['sport', 'travel'],                                     kw: ['skateboard', 'skate', 'papan'] },
  { id: 'parachute',          themes: ['sport', 'travel'],                                     kw: ['parasut', 'parachute', 'terjun', 'terbang'] },
  { id: 'joystick',           themes: ['sport', 'celebration'],                                kw: ['joystick', 'game', 'main'] },
  { id: 'video-game',         themes: ['sport', 'celebration'],                                kw: ['game', 'joystick', 'main', 'video game'] },
  { id: 'puzzle-piece',       themes: ['sport'],                                               kw: ['puzzle', 'teka-teki', 'menyusun'] },
  { id: 'chess-pawn',         themes: ['sport'],                                               kw: ['catur', 'chess', 'pion', 'strategi'] },
  { id: 'flexed-biceps',      themes: ['emoji', 'sport'],                                      kw: ['otot', 'kuat', 'strong', 'biceps'] },

  // ── Emoji / Ekspresi 😄 ───────────────────────────────
  { id: 'grinning-face',      themes: ['emoji', 'birthday', 'celebration'],                   kw: ['senyum', 'grin', 'bahagia', 'senang'] },
  { id: 'beaming-face-with-smiling-eyes', themes: ['emoji'],                                   kw: ['senyum', 'senang', 'bahagia', 'gembira'] },
  { id: 'face-with-tears-of-joy', themes: ['emoji', 'celebration'],                           kw: ['ketawa', 'lucu', 'haha', 'lol'] },
  { id: 'rolling-on-the-floor-laughing', themes: ['emoji'],                                    kw: ['ketawa', 'ngakak', 'lucu', 'lol'] },
  { id: 'smiling-face-with-smiling-eyes', themes: ['emoji'],                                   kw: ['senyum', 'senang', 'bahagia'] },
  { id: 'thinking-face',      themes: ['emoji'],                                               kw: ['pikir', 'think', 'hmm', 'bingung'] },
  { id: 'shushing-face',      themes: ['emoji'],                                               kw: ['diam', 'shush', 'rahasia', 'ssst'] },
  { id: 'clown-face',         themes: ['emoji', 'celebration'],                                kw: ['badut', 'clown', 'lucu', 'pesta'] },
  { id: 'ghost',              themes: ['emoji'],                                               kw: ['hantu', 'ghost', 'seram', 'halloween'] },
  { id: 'robot',              themes: ['emoji'],                                               kw: ['robot', 'mesin', 'teknologi'] },
  { id: 'alien',              themes: ['emoji'],                                               kw: ['alien', 'luar angkasa', 'ufo'] },
  { id: 'money-mouth-face',   themes: ['emoji'],                                               kw: ['uang', 'kaya', 'money', 'cuan'] },
  { id: 'star-struck',        themes: ['emoji', 'celebration'],                                kw: ['kagum', 'bintang', 'luar biasa', 'wow'] },
  { id: 'speech-balloon',     themes: ['emoji'],                                               kw: ['balon bicara', 'chat', 'ngobrol', 'teks'] },
  { id: 'thought-balloon',    themes: ['emoji'],                                               kw: ['pikiran', 'thought', 'mimpi', 'angan'] },
  { id: 'ok-hand',            themes: ['emoji'],                                               kw: ['oke', 'ok', 'bagus', 'mantap'] },
  { id: 'waving-hand',        themes: ['emoji'],                                               kw: ['lambaikan', 'halo', 'bye', 'hai'] },
  { id: 'raised-hand',        themes: ['emoji'],                                               kw: ['angkat tangan', 'halo', 'stop', 'hai'] },
  { id: 'crossed-fingers',    themes: ['emoji'],                                               kw: ['jari silang', 'luck', 'hoki', 'semoga'] },
];

export const getIconUrl = (id) =>
  `https://api.iconify.design/fluent-emoji-flat/${id}.svg?width=512&height=512`;
